### ISSUE TITLE
add a code of conduct document

### ISSUE THREAD

**Issue by igalic** [fruitfuljs/fruitfuljs#1]
We should select and add a code of conduct

My first choice would be [Contributor Covenant](http://contributor-covenant.org/).

This will require an email (list) for the people who're supposed to handle issues.

**Comment by Charlotteis** [comment]
My choice would be the wealljs code of conduct which I feel is much better and goes into much more detail. Contributor Covenant has gaps.

https://github.com/wealljs/weallbehave

It's also a node package.

**Comment by DKhalil** [comment]
I would go with the Contributer Covenant, mostly because of it's simplicity

**Comment by Charlotteis** [comment]
Contributor Covenant has bad enforcement policies, which is why it worries me / i don't use it.

**Comment by igalic** [comment]
given that we're incubating this within the the @WeAllJS community, i suggest also using their Code of Conduct then.

with @Voxpupuli, we've initially just used Puppet Inc.'s CoC (and still do, as an additional umbrella)

**Comment by Charlotteis** [comment]
awesome! I think @pup  is now linking to this CoC on our website, so I'ma close this.

**Comment by pup** [comment]
👍 ✨
